name: Flutter Test

on:
  pull_request:
    branches:
      - main

jobs:
  flutter_test:
    name: Run Flutter Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: subosito/flutter-action@v2
        with:
          channel: beta
          flutter-version: 3.23.0-0.1.pre
      - run: flutter pub get
      - run: flutter --version
      - run: flutter analyze
      - run: flutter test

